package:
  name: ghc
  version: 8.0.2

source:
  fn: ghc-8.0.2-src.tar.xz
  url: http://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-src.tar.xz

test:
  commands:
    - ghc --help

about:
  home: https://www.haskell.org/ghc/
  license: BSD
  summary: "GHC is a state-of-the-art, open source, compiler and interactive environment for the functional language Haskell."
