package:
  name: projectq
  version: "v0.3.0"

source:
  git_url: https://github.com/ProjectQ-Framework/ProjectQ.git

requirements:
  build:
    - python 3.6.*
    - numpy
    - matplotlib
    - gcc
    - pybind11

  run:
    - python 3.6.*
    - numpy
    - matplotlib
    - gcc
    - pybind11

test:
  imports:
    - projectq

about:
  home: https://projectq.ch
  license: Apache
  license_file: LICENSE
