package:
  name: fermilib
  version: "v0.1a0"

source:
  git_url: https://github.com/ProjectQ-Framework/FermiLib.git

requirements:
  build:
    - python >=3.0
    - numpy >=1.11.0
    - projectq 
    - scipy >=0.18.0
    - pytest
    - h5py
    - future

  run:
    - python >=3.0
    - numpy >=1.11.0
    - projectq 
    - scipy >=0.18.0
    - pytest
    - h5py
    - future

test:
  imports:
    - fermilib

about:
  home: https://github.com/ProjectQ-Framework/FermiLib
  license: Apache
  license_file: LICENSE
