package:
  name: openmpi
  version: 2.1.0

source:
  fn: openmpi-2.1.0.tar.bz2
  url: http://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.0.tar.bz2
  md5: 4838a5973115c44e14442c01d3f21d52

requirements:
  build:
    - gcc

about:
  home: http://www.open-mpi.org/
  license: new BSD  (http://www.open-mpi.org/community/license.php)
